### PR TITLE
Draft example of mini project with diagram

### PR DESCRIPTION
**Pull request by drpdr**
This is a draft PR to discuss how the splitter should operate. This PR may or may not be connected with new issues depending on how we want to relax possible security constraints. I think this is a small starting point to tackle some grouping/visibility issues (like #23 ) and work towards a more functional splitter. The diagram shows that now the splitter is creating a shared library for each function without considering any possible dependency. I believe that focusing on dependencies first (something I scheduled as "more challenging" in a previous roadmap) could help to solve even future problems we may encounter in bigger projects.

### CODE REVIEW

**Comment by ltratt** [comment]
Would it be easier to draw the imagined compartments as boxes containing sub-boxes?

**Comment by drpdr** [comment]
> Would it be easier to draw the imagined compartments as boxes containing sub-boxes?

OK, I'll draw another diagram.

**Comment by drpdr** [comment]
I am very sorry there was a spurious option on the command line (-f).

**Comment by drpdr** [comment]
> I am very sorry there was a spurious option on the command line (-f).

But it seems it didn't affect the PR, luckily.

**Comment by drpdr** [comment]
The (updated) diagram in [745c857] shows what the splitter currently does.

**Comment by drpdr** [comment]
Instead, [7478f4f] shows what could be a different approach.

**Comment by drpdr** [comment]
So, I think the issue here is modifying the granularity of the splitter. Yes, the goal is splitting a binary into functions as separated shared objects, however we may rethink of something in-between the fine-grained splitting (current situation) and a more coarse-grained result. Probably this PR should have been an Issue, but I thought it would have included too much code and opted for a draft PR.

**Comment by ltratt** [comment]
OK I now understand the diagram more-or-less.

Is the purpose of this PR to say "the splitter already splits this but does it in the wrong way" or ... ?

**Comment by drpdr** [comment]
> Is the purpose of this PR to say "the splitter already splits this but does it in the wrong way" or ... ?

More or less. The idea was to show "how a split binary should look like" so we can understand other possible issues we may encounter. The splitter creates a shared object with a single function (or global variable) accessible by every other function in the program. I *think* what he does is not what we want to achieve.

**Comment by ltratt** [comment]
Are you saying that the splitter currently splits the program in such a way that it can't be compiled?

**Comment by drpdr** [comment]
> Are you saying that the splitter currently splits the program in such a way that it can't be compiled?

No, currently I can split and join this simple project without problems.

**Comment by ltratt** [comment]
OK, so as you're probably guessing, I'm confused :) I don't understand what the current problem is or what your proposed solution is.

**Comment by drpdr** [comment]
> OK, so as you're probably guessing, I'm confused :) I don't understand what the current problem is or what your proposed solution is.

Alright, let me rethink about it.

**Comment by drpdr** [comment]
@ltratt, should we close this draft PR, then?

**Comment by ltratt** [comment]
Your decision.

**Comment by ltratt** [comment]
@drpdr ping.

**Comment by drpdr** [comment]
After carefully consideration this draft PR is not needed. Better focusing on the issues we have while testing real world programs and iterate.

**Pull request closed without merging**
