### PR TITLE
Fix extern internal/hidden variables

### PR DESCRIPTION
**Pull request by drpdr**
Extern variables marked as `internal/hidden` should not be touched. This simple fix will solve Issue #31.

### CODE REVIEW

**Comment by drpdr** [comment]
bors try

**Comment by ltratt** [comment]
Let's add a test to this PR too.

**Comment by drpdr** [comment]
> Let's add a test to this PR too.

OK.

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
> Let's add a test to this PR too.

In [dc00596](https://github.com/capablevms/llvm-function-split/pull/32/commits/dc005964e9588801d6c711a01ddc097a0bc3c2d3).

**Comment by drpdr** [comment]
Something does seem right, though.

**Comment by drpdr** [comment]
> Something doesn't seem right, though.

Oh, I know.

**Comment by drpdr** [comment]
bors try

**Comment by ltratt** [comment]
Please squash.

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors try

**Comment by ltratt** [comment]
Please squash.

**Comment by drpdr** [comment]
> Please squash.

Done.

**Comment by drpdr** [comment]
A little returning "glitch" I've put on my TODO list again. Try again @ltratt, please.

**Comment by ltratt** [comment]
I think we need to fix whatever the glitch is before trying again.

**Comment by drpdr** [comment]
There was something stuck probably from previous tests with buildbot. Now, it should work. I do not think is something to worry about but I'll double check.

**Pull request merged**
