### PR TITLE
Add --config to simplify CFLAGS

### PR DESCRIPTION
**Pull request by drpdr**
Now we can use `--config cheribsd-ARCH-purecap`.

### CODE REVIEW

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors try-

**Comment by drpdr** [comment]
bors try

**Comment by drpdr** [comment]
bors try-

**Comment by drpdr** [comment]
@ltratt ready for review.

**Comment by ltratt** [comment]
Please squash.

**Comment by drpdr** [comment]
> Please squash.

Squashed.

**Pull request merged**
